name: Generate HTML from GitHub Issues
on:
  issues:
    types: [opened, edited, deleted]

jobs:
  generate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install marked

      - name: Install other dependencies
        run: npm install

      - name: Execute corresponding script
        run: |
          if [ "${{ github.event_name }}" = "issues" ]; then
            if [ "${{ github.event.action }}" = "opened" ]; then
              node generate-html.js
            elif [ "${{ github.event.action }}" = "edited" ]; then
              node edit-html.js
            elif [ "${{ github.event.action }}" = "deleted" ]; then
              node delete-html.js
            fi
          fi

      - name: Commit and push changes
        if: github.event_name != 'deleted'  # Only commit and push changes for non-delete events
        run: |
          git config --global user.email "limjilab@gmail.com"
          git config --global user.name "imzii"
          git add .
          git commit -m "Generate/Update HTML from GitHub Issues"
          git push
